version: 0.2
env:
  secrets-manager:
    DOCKERHUB_PASS: "DockerLogin:DOCKER_P"
    DOCKERHUB_USERNAME: "DockerLogin:DOCKER_U"
    db_host: "DBSInfo:host"
    db_user: "DBSInfo:username"
    db_password: "DBSInfo:password"
    db_port: "DBSInfo:port"
    db_database: "DBSInfo:dbname"
phases:
  pre_build:
    on-failure: CONTINUE
    commands:
      - yarn install
      - cd server
      - yarn test
  build:
    commands:
      - cd ..
      - echo Building nginx, client, and backend images
      - docker build -t ardiank/nginx -f ./nginx/Dockerfile ./nginx
      - cd client && docker build -t ardiank/client .
      - cd .. && docker build -t ardiank/backend -f Dockerfile .
      - echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
  post_build:
    commands:
      - echo Pushing images to Docker Hub
      - docker push ardiank/nginx
      - docker push ardiank/client
      - docker push ardiank/backend
