version: '3.3'
services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  client:
      build: 
        context: ./client
        dockerfile: Dockerfile
      #ports:
      #   - "5173:5173"
      container_name: client

  backend:
      build: 
        context: .
        dockerfile: Dockerfile
      #ports:
      #  - "3000:3000"
      container_name: backend
