on:
  push:
    branches: [ main, unit_test ]
  workflow_dispatch:
  
jobs:
  unit_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Setup for tests and builds
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Test Server functions and services
      run: yarn install && cd server && yarn test
      working-directory: .
