on:
  push:
    branches:
    - unit_test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test Server functions and services
      run: yarn test
      working-directory: ./server
    - name: Client build error check
      run: yarn build
      working-directory: ./client
