on:
  push:
    branches: [ main, unit_test ]
  pull_request:
    branches: [ main, unit_test ]
  workflow_dispatch:
  
jobs:
  unit_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup for tests and builds
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Test Server functions and services
      run: echo "DATABASE_PASSWORD: $DB_PASSWORD" && env && yarn install && cd server && yarn test
      working-directory: .
